const recipes = [
    {
      id: 1,
      title: 'Spaghetti Bolognese',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$10.99',
      quantity: '1 serving',
      category: 'Italian',
      description: 'Spaghetti pasta served with a rich, hearty meat sauce.',
    },
    {
      id: 2,
      title: 'Chicken Alfredo',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$12.49',
      quantity: '1 serving',
      category: 'Italian',
      description: 'Creamy fettuccine pasta with grilled chicken in a parmesan sauce.',
    },
    {
      id: 3,
      title: 'Sushi Rolls',
      image:'https://picsum.photos/id/237/200/300',
      price: '$14.99',
      quantity: '6 pieces',
      category: 'Japanese',
      description: 'Assorted sushi rolls with fresh fish, rice, and vegetables.',
    },
    {
      id: 4,
      title: 'Taco Salad',
      image:'https://picsum.photos/id/237/200/300',
      price: '$8.99',
      quantity: '1 serving',
      category: 'Mexican',
      description: 'A fresh salad with seasoned ground beef, beans, corn, and taco toppings.',
    },
    {
      id: 5,
      title: 'Miso Soup',
      image:'https://picsum.photos/id/237/200/300',
      price: '$6.49',
      quantity: '1 serving',
      category: 'Japanese',
      description: 'A traditional Japanese soup made with miso paste, tofu, and seaweed.',
    },
    {
      id: 6,
      title: 'Greek Salad',
      image:'https://picsum.photos/id/237/200/300',
      price: '$9.99',
      quantity: '1 serving',
      category: 'Mediterranean',
      description: 'Fresh salad with tomatoes, cucumbers, olives, feta cheese, and olive oil dressing.',
    },
    {
      id: 7,
      title: 'Pad Thai',
      image:'https://picsum.photos/id/237/200/300',
      price: '$11.99',
      quantity: '1 serving',
      category: 'Thai',
      description: 'Stir-fried rice noodles with tofu, shrimp, peanuts, and vegetables.',
    },
    {
      id: 8,
      title: 'Chicken Shawarma',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$13.99',
      quantity: '1 serving',
      category: 'Middle Eastern',
      description: 'Grilled chicken wrapped in pita bread with tahini sauce and vegetables.',
    },
    {
      id: 9,
      title: 'Caprese Salad',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$7.99',
      quantity: '1 serving',
      category: 'Italian',
      description: 'Fresh salad with tomatoes, mozzarella cheese, basil, and balsamic glaze.',
    },
    {
      id: 10,
      title: 'Peking Duck',
      image:'https://picsum.photos/id/237/200/300',
      price: '$17.99',
      quantity: '1 serving',
      category: 'Chinese',
      description: 'Crispy roasted duck served with pancakes, hoisin sauce, and scallions.',
    },
    {
      id: 11,
      title: 'Beef Bourguignon',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$16.99',
      quantity: '1 serving',
      category: 'French',
      description: 'Slow-cooked beef stew with red wine, mushrooms, and onions.',
    },
    {
      id: 12,
      title: 'Falafel Wrap',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$9.49',
      quantity: '1 serving',
      category: 'Middle Eastern',
      description: 'Falafel balls wrapped in pita bread with vegetables and tahini sauce.',
    },
    {
      id: 13,
      title: 'Lasagna',
      image :'https://picsum.photos/id/237/200/300',
      price: '$11.99',
      quantity: '1 serving',
      category: 'Italian',
      description: 'Layers of pasta, ground meat, cheese, and tomato sauce baked to perfection.',
    },
    {
      id: 14,
      title: 'Chicken Curry',
      image: 'https://picsum.photos/id/237/200/300',
      price: '$12.99',
      quantity: '1 serving',
      category: 'Indian',
      description: 'Savory chicken cooked in a flavorful blend of spices and curry sauce.',
    },
    // {
    //   id: 15,
    //   title: 'Key Lime Pie',
    //   image: 'https://example.com/key_lime_pie.jpg',
    //   price: '$8.99',
    //   quantity: '1 slice',
    //   category: 'Dessert',
    //   description: 'A tangy and sweet pie made with key lime juice, graham cracker crust
    // }
]  


export default recipes;